config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"
  get  "/home/about", to: "home#about", as: "about"
  devise_for :users
  # usersのルーティングがdeviseのやつより上にあると、そっちのルーティングが優先されてバグるらしい
  # 参考：https://qiita.com/iamtsujikenta/items/8f8e122ce429c2920425
  resources :books, only: [:index, :show, :create, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user

    validates :title, :body, presence: true
    validates :body, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.page(params[:page])
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.page(params[:page])
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: Book.new do |f| %>
   <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div>
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      </div>

      <%= form_with model: @book do |f| %>
      <div class="form-group">
       <label for="inputTitle">Title</label><br>
        <%= f.text_field :title, id:"inputTitle"%>
      </div>
      <div class="form-group">
        <label for="inputBody">Opinion</label><br>
        <%= f.text_area :body, id:"inputBody" %>
      </div>
      <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>

      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
                <%= image_tag current_user.get_image(100,100) %>
                <table class="table">
                    <tbody>
                        <tr></tr>
                        <tr>
                            <th>name</th>
                            <th><%= current_user.name %></th>
                        </tr>
                        <tr>
                        <th>introduction</th>
                        <th><%= current_user.introduction %></th>
                        </tr>
                    </tbody>
                </table>
                <div class="row">
                <%= link_to(edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block") do %>
                  <i class="fas fa-user-cog"></i>
                <% end %>
                </div>
                <%= render 'books/list', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                </tr>
                </thead>
                <tbody>
                    <% @books.each do |book| %>
                        <tr>
                            <td>
                            <%= link_to user_path(book.user_id) do %>
                                <%= image_tag book.user.get_image(100,100) %><br>
                            <% end %>
                            </td>
                            <td><%= link_to "#{book.title}", book_path(book) %></td>
                            <td><%= book.body %></td>
                        </tr>
                    <% end %>
                    <%= paginate @books %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div>
    <%= flash[:notice] %>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h2>User info</h2>
            <%= image_tag @book.user.get_image(100,100) %>
            <table class="table">
                <tbody>
                    <tr></tr>
                    <tr>
                        <th>name</th>
                        <th><%= @book.user.name %></th>
                    </tr>
                    <tr>
                    <th>introduction</th>
                    <th><%= @book.user.introduction %></th>
                    </tr>
                </tbody>
            </table>
            <div class="row">
            <%= link_to(edit_user_path(@book.user_id), class: "btn btn-outline-secondary btn-block") do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
            </div>
            <%= render 'books/list', book: @book %>
            </div>
            <div class="col-md-8 offset-md-1">
              <h2>Book detail</h2>
              <table class="table">
                <tbody>
                    <tr>
                        <td>
                        <%= link_to user_path(@book.user_id) do %>
                            <%= image_tag @book.user.get_image(100,100) %><br>
                            <%= @book.user.name %>
                        <% end %>
                        </td>
                        <td><%= link_to "#{@book.title}", book_path(@book) %></td>
                        <td><%= @book.body %></td>

                        <% if current_user == @book.user %>
                            <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
                            <td><%= link_to "Destroy", book_path(@book), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "本当に消しますか？" }  %></td>
                        <% end %>
                    </tr>
                </tbody>
              </table>
            </div>
        </div>
    </div>