config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"
  get  "/home/about", to: "home#about", as: "about"
  devise_for :users
  # usersのルーティングがdeviseのやつより上にあると、そっちのルーティングが優先されてバグるらしい
  # 参考：https://qiita.com/iamtsujikenta/items/8f8e122ce429c2920425
  resources :books, only: [:index, :show, :create, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to(user_path(id: current_user.id), class: "nav-link text-light") do %>
                  <i class="fas fa-home" style="color: #ffffff;"></i>
                  Home
                <% end %>
              </li>
              <li>
                <%= link_to(users_path, class: "nav-link text-light") do %>
                  <i class="fas fa-users" style="color: #ffffff;"></i>
                  Users
                <% end %>
              </li>
              <li>
                <%= link_to(books_path, class:"nav-link text-light") do %>
                  <i class="fas fa-book-open" style="color: #ffffff;"></i>
                  Books
                <% end %>
              </li>
              <li>
                <%= link_to(destroy_user_session_path,class: "nav-link text-light", method: :delete) do %>
                  <i class="fas fa-sign-out-alt" style="color: #ffffff;"></i>
                  Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to(root_path, class: "nav-link text-light") do %>
                   <i class="fas fa-home" style="color: #ffffff;"></i>
                   Home
                <% end %>
              </li>
              <li>
                <%= link_to(about_path, class: "nav-link text-light") do %>
                  <i class="fas fa-link" style="color: #ffffff;"></i>
                  About
                <% end %>
              </li>
              <li>
                <%= link_to(new_user_registration_path, class:"nav-link text-light") do %>
                  <i class="fas fa-user-plus" style="color: #ffffff;"></i>
                  Sign up
                <% end %>
              </li>
              <li>
                <%= link_to(new_user_session_path,class: "nav-link text-light") do %>
                  <i class="fas fa-sign-in-alt" style="color: #ffffff;"></i>
                  Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>